version: "3.9"
services:
  application:
    image: dev/vind-software/fira-server/application:0.2
    build: 
      context: ./
      dockerfile: ./Infra/Application/Dockerfile.dev
    depends_on:
      - relational-db
      - reverse-proxy
  relational-db:
    image: dev/vind-software/fira-server/relational-db:0.2
    build: 
      context: ./
      dockerfile: ./Infra/Postgres/Dockerfile.dev
    ports:
      - "5432:5432"
  reverse-proxy:
    image: dev/vind-software/fira-server/reverse-proxy:0.2
    build: 
      context: ./
      dockerfile: ./Infra/Nginx/Dockerfile.dev
    ports:
      - "80:80"
networks:
  default:
    name: fira-server-dev-network