version: "3.9"
services:
  application:
    image: dev/vind-software/fira-server/application:00.00.001
    build: 
      context: ./
      dockerfile: ./infra/Images/Application/Dockerfile.dev
    depends_on:
      - relational-db
      - reverse-proxy
    environment:
      FIRASERVER_DB__Relational__Host: ${FIRASERVER_DB__Relational__Host}
      FIRASERVER_DB__Relational__Database: ${FIRASERVER_DB__Relational__Database}
      FIRASERVER_DB__Relational__Username: ${FIRASERVER_DB__Relational__Username}
      FIRASERVER_DB__Relational__Password: ${FIRASERVER_DB__Relational__Password}
    volumes:
        - ./src:/app
        - /app/Api/obj/ 
        - /app/Api/bin/
        - /app/Application/obj/ 
        - /app/Application/bin/
        - /app/Core/Domain/obj/ 
        - /app/Core/Domain/bin/
        - /app/Core/Service/obj/ 
        - /app/Core/Service/bin/
        - /app/DI/obj/ 
        - /app/DI/bin/
        - /app/Infra/Dal/obj/ 
        - /app/Infra/Dal/bin/

  relational-db:
    image: dev/vind-software/fira-server/relational-db:00.00.001
    build: 
      context: ./
      dockerfile: ./infra/Images/Postgres/Dockerfile.dev
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./infra/Images/Postgres/DevData
        target: /var/lib/postgresql/data

  reverse-proxy:
    image: dev/vind-software/fira-server/reverse-proxy:00.00.001
    build: 
      context: ./
      dockerfile: ./infra/Images/Nginx/Dockerfile.dev
    ports:
      - "80:80"

  application-unit-test:
    image: dev/vind-software/fira-server/application-unit-test:00.00.001
    build:
      context: ./
      dockerfile: ./infra/Images/Tests/Dockerfile.unit
    profiles:
      - unitTests
  
  application-integration-test:
    image: dev/vind-software/fira-server/application-integration-test:00.00.001
    build:
      context: ./
      dockerfile: ./infra/Images/Tests/Dockerfile.integration
    profiles:
      - integrationTests

networks:
  default:
    name: fira-server-dev-network