FROM mcr.microsoft.com/dotnet/sdk:6.0 AS fira-server-webserver-build-env
WORKDIR /app

# COPY fira-server.csproj ./
# COPY ./src ./
# RUN dotnet restore

# COPY ./src ./
#RUN dotnet publish -o build

# FROM mcr.microsoft.com/dotnet/aspnet:6.0
# WORKDIR /app

# COPY --from=fira-server-webserver-build-env /app/build .
ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT=Development

ENV FIRASERVER_DB__Relational__Host=relational-db

# ENTRYPOINT [ "dotnet", "FiraServer.Api.dll" ]
ENTRYPOINT ["dotnet", "watch", "run", "--project=Api/FiraServer.api.csproj", "--urls=http://*:5000"]